### ISSUE TITLE
Docker does nothing on run

### ISSUE THREAD

**Issue by julianxhokaxhiu** [binhex/arch-koel#4]
I am trying to run your docker and what I get is:

```
Created by...
___.   .__       .__                   
\_ |__ |__| ____ |  |__   ____ ___  ___
 | __ \|  |/    \|  |  \_/ __ \\  \/  /
 | \_\ \  |   |  \   Y  \  ___/ >    < 
 |___  /__|___|  /___|  /\___  >__/\_ \
     \/        \/     \/     \/      \/
   https://hub.docker.com/u/binhex/

2017-04-04 21:52:01.575906 [info] System information Linux 6ce834f1ba5e 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux
2017-04-04 21:52:01.686572 [warn] PUID not defined (via -e PUID), defaulting to '99'
2017-04-04 21:52:01.778204 [warn] PGID not defined (via -e PGID), defaulting to '100'
2017-04-04 21:52:01.958827 [warn] UMASK not defined (via -e UMASK), defaulting to '000'
2017-04-04 21:52:02.046786 [info] Setting permissions recursively on volume mappings...
```

Is it normal? This is the way I am running it: https://github.com/julianxhokaxhiu/vps-powered-by-docker/blob/master/modules/koel.sh

**Comment by binhex** [comment]
the last line you see is where it recursively sets permissions as defined via  PUID and PGID, this can take some time if the root folder you have specified has a lot of other files and sub folders, ideally i would recommend NOT having /config in a folder with existing files and instead create an empty folder.

so in short i dont believe this is a bug, you should see the container start after its finishing setting permissions, or alternatively define /config as a empty folder on the host.

**Comment by julianxhokaxhiu** [comment]
Hi,

My config folder is an empty folder and the docker is not starting sorry :/

It's not first time I manage them. Did you try the latest one? What do you get on your side?

Thank you in advance

**Comment by binhex** [comment]
ok there were a couple of bugs i have literally just squashed, neither of which should stop the creation of files/folders in /config but its worth you pulling down the latest image and give it a spin and see what we get then.

**Comment by julianxhokaxhiu** [comment]
Thanks, I'll provide some feedback later :)

**Comment by julianxhokaxhiu** [comment]
Allright, tested right now and I still get the same log:

```
Created by...
___.   .__       .__                   
\_ |__ |__| ____ |  |__   ____ ___  ___
 | __ \|  |/    \|  |  \_/ __ \\  \/  /
 | \_\ \  |   |  \   Y  \  ___/ >    < 
 |___  /__|___|  /___|  /\___  >__/\_ \
     \/        \/     \/     \/      \/
   https://hub.docker.com/u/binhex/

2017-04-05 21:35:32.619457 [info] System information Linux 0fe5b05dd06c 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux
2017-04-05 21:35:32.733867 [warn] PUID not defined (via -e PUID), defaulting to '99'
2017-04-05 21:35:32.833847 [warn] PGID not defined (via -e PGID), defaulting to '100'
2017-04-05 21:35:33.066110 [warn] UMASK not defined (via -e UMASK), defaulting to '000'
2017-04-05 21:35:33.151614 [info] Setting permissions recursively on volume mappings...
```

Now the question is: why is not even starting the Database or any other script. What is wrong? I am using the latest Docker Engine on Arch Linux x64:

```sh
~ # uname -a
Linux NAS 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux

~ # docker -v
Docker version 17.03.1-ce, build c6d412e329
```

**Comment by binhex** [comment]
im not sure what is going on here at all, all that line does is set permissions inside the running container, it def shouldn't cause significant IO issues, have you tried running another container?, if your getting the same issue then i would assume you have some problems with your docker installation.

**Comment by julianxhokaxhiu** [comment]
I am currently running Nginx Proxy, OwnCloud and other dockers there. All running fine :)

I think your chown command is touching some special folders, which for some reason, because I am using `overlay2` storage driver ( set by default from the Docker Engine btw ) I can trigger this special case, where chown is not able to run properly and maybe is "hanging and retrying until death".

Is it really required that command line to make the Docker run properly?

**Comment by binhex** [comment]
im afraid it is required, so there is no getting around it, you could try storage driver btrfs or devicemapper if available.

**Comment by raphaelyancey** [comment]
Same problem. Changing the volume driver can be done with https://docs.docker.com/compose/compose-file/compose-file-v2/#driver in a compose file right? Or do I have to change the whole Docker storage driver?

**Comment by fuzzymannerz** [comment]
I have the same issue when running:

```bash
sudo docker run -d \
    -p 8050:8050 \
    --name=koel \
    -v /hdd2/media/music:/media \
    -v /apps/docker/koel/config:/config \
    -v /etc/localtime:/etc/localtime:ro \
    -e PHP_MEMORY_LIMIT=256 \
    -e FASTCGI_READ_TIMEOUT=6000 \
    -e UMASK=000 \
    -e PUID=1000 \
    -e PGID=1000 \
    binhex/arch-koel
```

I get this forever:

```
2018-08-01 14:26:13.809721 [info] System information Linux 3b0c3a0b6702 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
2018-08-01 14:26:13.877051 [info] PUID defined as '1000'
2018-08-01 14:26:14.365758 [info] PGID defined as '1000'
2018-08-01 14:26:14.729886 [info] UMASK defined as '000'
2018-08-01 14:26:14.785605 [info] Setting permissions recursively on volume mappings...
```
If I run it again then the last line says `Permissions already set for volume mappings` and hangs there instead.

Am I missing something or is there something I should check first? The `/apps/docker/koel/config` DIR does not already exist and gets created so I'm thinking maybe something to do with the media mount?

Any help is appreciated. :)

**Comment by spikespaz** [comment]
Would love an update

**Comment by julianxhokaxhiu** [comment]
Looks like we can fix the issue ourself if we build the container using the new `DOCKER_BUILDKIT=1` feature. See https://docs.docker.com/develop/develop-images/build_enhancements/

Although I didn't test it myself as I don't have the need at the moment, so any feedback is appreciated.
