### ISSUE TITLE
media scanning is broken

### ISSUE THREAD

**Issue by coollorenzo** [binhex/arch-koel#5]
i get the following server error when trying to scan for media
![image](https://cloud.githubusercontent.com/assets/11248198/24722538/57549c70-1a44-11e7-9047-ace12bf2aa49.png)
still can't get the docker running properly  :/

**Comment by binhex** [comment]
That looks like a potential koel bug, it maybe triggered by badly tagged media, so try scanning a small subset of your media, if this succeeds then try expanding ithis until it blows up. 

just to give you some hope, i have successfully scanned my entire music collection using the latest version of koel. i did however have to tweak the timeout value in the .env config file and set it to 6000 secs in order to give koel enough time to scan (yes its damn slow).

**Comment by coollorenzo** [comment]
smaller sets work just fine but I need this one to work the meta data is generated by emby media server and I manually checked the album.nfo and all the data was correct also the image 'folder.jpg' excists. Tried deleting both album.nfo and folder.jpg but this also didn't help tried deleting folder and pasting files in new folder with same name also didn't work

**Comment by binhex** [comment]
> Should I post this isue to the koel developers?

whilst i cant say the problem your seeing isnt related to docker, i think there is a possibility it is a pure coding issue with koel, so yeah thats probably the next logical step at this point.

just a fyi, i have had scanning issues with koel historically, it seems a bit better as of late but it never has felt solid, and most definitely is VERY slow to index music.

incase you want to look at other solutions you could always give libresonic a go, i have very good results with this, its fast, pretty stable and for me beats koel hands down, link:-

https://github.com/binhex/arch-libresonic

**Comment by binhex** [comment]
This looks to be now fixed in the latest version 3.6.1

**Comment by coollorenzo** [comment]
It's fixed now thanks.
btw I prever koel over libresonic because it's looks way cooler and is a lot easier to use(when it works atleast)

**Comment by binhex** [comment]
Yes I spotted it got fixed in 3.6.1 I disagree about ease of use for libresonic vs koel especially when you factor in android support via things like dsub, but choice is a good thing, that's why I will carry on supporting koel :-)
